version: '2'
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/yobit-bot
  db:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data